using namespace std;

void draw(TString root_file) {
    TCanvas *c = new TCanvas("c","c",1100,750);
    gPad->SetLogy();
    TFile *f2 = new TFile(root_file);
    TH1D* HistMjj = (TH1D*) f2->Get("HistMjj");
    TH1D* HistMjj_TruthGG = (TH1D*) f2->Get("HistMjj_TruthGG");
    TH1D* HistMjj_TruthGJ = (TH1D*) f2->Get("HistMjj_TruthGJ");
    TH1D* HistMjj_TruthQG = (TH1D*) f2->Get("HistMjj_TruthQG");
    TH1D* HistMjj_TruthQQ = (TH1D*) f2->Get("HistMjj_TruthQQ");
    TH1D* HistMjj_GG = (TH1D*) f2->Get("HistMjj_GG");
    TH1D* HistMjj_GJ = (TH1D*) f2->Get("HistMjj_GJ");
    TH1D* HistMjj_QG = (TH1D*) f2->Get("HistMjj_QG");
    TH1D* HistMjj_QQ = (TH1D*) f2->Get("HistMjj_QQ");
    TH1D* HistLeadingJetPt = (TH1D*) f2->Get("HistLeadingJetPt");
    TH1D* HistLeadingJetPt_TruthGG = (TH1D*) f2->Get("HistLeadingJetPt_TruthGG");
    TH1D* HistLeadingJetPt_TruthGJ = (TH1D*) f2->Get("HistLeadingJetPt_TruthGJ");
    TH1D* HistLeadingJetPt_TruthQG = (TH1D*) f2->Get("HistLeadingJetPt_TruthQG");
    TH1D* HistLeadingJetPt_TruthQQ = (TH1D*) f2->Get("HistLeadingJetPt_TruthQQ");
    TH1D* HistLeadingJetPt_GG = (TH1D*) f2->Get("HistLeadingJetPt_GG");
    TH1D* HistLeadingJetPt_GJ = (TH1D*) f2->Get("HistLeadingJetPt_GJ");
    TH1D* HistLeadingJetPt_QG = (TH1D*) f2->Get("HistLeadingJetPt_QG");
    TH1D* HistLeadingJetPt_QQ = (TH1D*) f2->Get("HistLeadingJetPt_QQ");
    TH1D* HistSubJetPt = (TH1D*) f2->Get("HistSubJetPt");
    TH1D* HistSubJetPt_TruthGG = (TH1D*) f2->Get("HistSubJetPt_TruthGG");
    TH1D* HistSubJetPt_TruthGJ = (TH1D*) f2->Get("HistSubJetPt_TruthGJ");
    TH1D* HistSubJetPt_TruthQG = (TH1D*) f2->Get("HistSubJetPt_TruthQG");
    TH1D* HistSubJetPt_TruthQQ = (TH1D*) f2->Get("HistSubJetPt_TruthQQ");
    TH1D* HistSubJetPt_GG = (TH1D*) f2->Get("HistSubJetPt_GG");
    TH1D* HistSubJetPt_GJ = (TH1D*) f2->Get("HistSubJetPt_GJ");
    TH1D* HistSubJetPt_QG = (TH1D*) f2->Get("HistSubJetPt_QG");
    TH1D* HistSubJetPt_QQ = (TH1D*) f2->Get("HistSubJetPt_QQ");
    TH1D* HistNTrk = (TH1D*) f2->Get("HistNTrk");
    TH1D* HistNTrk_G = (TH1D*) f2->Get("HistNTrk_G");
    TH1D* HistNTrk_Q = (TH1D*) f2->Get("HistNTrk_Q");
    

    auto mtlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistMjj->SetAxisRange(400., 12000.,"X");
    HistMjj->SetLineColor(1);
    HistMjj->Draw();
    mtlegend->AddEntry(HistMjj, "Mjj", "l");
    HistMjj_TruthGG->SetLineColor(2);
    HistMjj_TruthGG->Draw("same");
    mtlegend->AddEntry(HistMjj_TruthGG, "TruthGG", "l");
    HistMjj_TruthQG->SetLineColor(3);
    HistMjj_TruthQG->Draw("same");
    mtlegend->AddEntry(HistMjj_TruthQG, "TruthQG", "l");
    HistMjj_TruthQQ->SetLineColor(7);
    HistMjj_TruthQQ->Draw("same");
    mtlegend->AddEntry(HistMjj_TruthQQ, "TruthQQ", "l");
    mtlegend->Draw();
    c->SaveAs(root_file + "mjjt.png");
    
    auto mlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistMjj->SetAxisRange(400., 12000.,"X");
    HistMjj->SetLineColor(1);
    HistMjj->Draw();
    mlegend->AddEntry(HistMjj, "Mjj", "l");
    HistMjj_GG->SetLineColor(2);
    HistMjj_GG->Draw("same");
    mlegend->AddEntry(HistMjj_GG, "GG", "l");
    HistMjj_QG->SetLineColor(3);
    HistMjj_QG->Draw("same");
    mlegend->AddEntry(HistMjj_QG, "QG", "l");
    HistMjj_QQ->SetLineColor(7);
    HistMjj_QQ->Draw("same");
    mlegend->AddEntry(HistMjj_QQ, "QQ", "l");
    mlegend->Draw();
    c->SaveAs(root_file + "mjj.png");
    
    auto lpttlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistLeadingJetPt->SetAxisRange(400., 8200.,"X");
    HistLeadingJetPt->SetLineColor(1);
    HistLeadingJetPt->Draw();
    lpttlegend->AddEntry(HistLeadingJetPt, "LPt", "l");
    HistLeadingJetPt_TruthGG->SetLineColor(2);
    HistLeadingJetPt_TruthGG->Draw("same");
    lpttlegend->AddEntry(HistLeadingJetPt_TruthGG, "TruthGG", "l");
    HistLeadingJetPt_TruthQG->SetLineColor(3);
    HistLeadingJetPt_TruthQG->Draw("same");
    lpttlegend->AddEntry(HistLeadingJetPt_TruthQG, "TruthQG", "l");
    HistLeadingJetPt_TruthQQ->SetLineColor(7);
    HistLeadingJetPt_TruthQQ->Draw("same");
    lpttlegend->AddEntry(HistLeadingJetPt_TruthQQ, "TruthQQ", "l");
    lpttlegend->Draw();
    c->SaveAs(root_file + "LPtt.png");
    
    auto lptlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistLeadingJetPt->SetAxisRange(400., 8200.,"X");
    HistLeadingJetPt->SetLineColor(1);
    HistLeadingJetPt->Draw();
    lptlegend->AddEntry(HistLeadingJetPt, "LPt", "l");
    HistLeadingJetPt_GG->SetLineColor(2);
    HistLeadingJetPt_GG->Draw("same");
    lptlegend->AddEntry(HistLeadingJetPt_GG, "GG", "l");
    HistLeadingJetPt_QG->SetLineColor(3);
    HistLeadingJetPt_QG->Draw("same");
    lptlegend->AddEntry(HistLeadingJetPt_QG, "QG", "l");
    HistLeadingJetPt_QQ->SetLineColor(7);
    HistLeadingJetPt_QQ->Draw("same");
    lptlegend->AddEntry(HistLeadingJetPt_QQ, "QQ", "l");
    lptlegend->Draw();
    c->SaveAs(root_file + "LPt.png");
    
    auto spttlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistSubJetPt->SetAxisRange(400., 8200.,"X");
    HistSubJetPt->SetLineColor(1);
    HistSubJetPt->Draw();
    spttlegend->AddEntry(HistSubJetPt, "SPt", "l");
    HistSubJetPt_TruthGG->SetLineColor(2);
    HistSubJetPt_TruthGG->Draw("same");
    spttlegend->AddEntry(HistSubJetPt_TruthGG, "TruthGG", "l");
    HistSubJetPt_TruthQG->SetLineColor(3);
    HistSubJetPt_TruthQG->Draw("same");
    spttlegend->AddEntry(HistSubJetPt_TruthQG, "TruthQG", "l");
    HistSubJetPt_TruthQQ->SetLineColor(7);
    HistSubJetPt_TruthQQ->Draw("same");
    spttlegend->AddEntry(HistSubJetPt_TruthQQ, "TruthQQ", "l");
    spttlegend->Draw();
    c->SaveAs(root_file + "SPtt.png");
    
    auto sptlegend = new TLegend(0.8, 0.28, 0.89, 0.75);
    HistSubJetPt->SetAxisRange(400., 8200.,"X");
    HistSubJetPt->SetLineColor(1);
    HistSubJetPt->Draw();
    sptlegend->AddEntry(HistSubJetPt, "SPt", "l");
    HistSubJetPt_GG->SetLineColor(2);
    HistSubJetPt_GG->Draw("same");
    sptlegend->AddEntry(HistLeadingJetPt_GG, "GG", "l");
    HistSubJetPt_QG->SetLineColor(3);
    HistSubJetPt_QG->Draw("same");
    sptlegend->AddEntry(HistSubJetPt_QG, "QG", "l");
    HistSubJetPt_QQ->SetLineColor(7);
    HistSubJetPt_QQ->Draw("same");
    sptlegend->AddEntry(HistSubJetPt_QQ, "QQ", "l");
    sptlegend->Draw();
    c->SaveAs(root_file + "SPt.png");

    auto trklegend = new TLegend(0.83, 0.38, 0.89, 0.75);
    HistNTrk->SetAxisRange(-10., 100.,"X");
    HistNTrk->SetLineColor(1);
    HistNTrk->Draw();
    trklegend->AddEntry(HistNTrk, "NTrk", "l");
    HistNTrk_G->SetLineColor(2);
    HistNTrk_G->Draw("same");
    trklegend->AddEntry(HistNTrk_G, "G", "l");
    HistNTrk_Q->SetLineColor(7);
    HistNTrk_Q->Draw("same");
    trklegend->AddEntry(HistNTrk_Q, "Q", "l");
    trklegend->Draw();
    c->SaveAs(root_file + "NTrk.png");

}
